---
- name: fetch nvm installer
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v{{nvm_version}}/install.sh
    dest: /tmp/install.sh
- name: install nvm
  shell: bash /tmp/install.sh
- name: install node.js
  shell: ". ~/.nvm/nvm.sh && nvm install {{nodejs_version}}"
- name: set global version of node.js
  shell: ". ~/.nvm/nvm.sh && nvm alias default {{nodejs_version}}"
