---
- hosts: localhost
  connection: local
  become: no
  roles:
    - nvm
    - homebrew
    - homebrew-cask
    - dotfiles
  vars:
    nvm_version: 0.33.8
    nodejs_version: 9.4.0
    homebrew_taps:
      - homebrew/php
    homebrew_packages:
      - vim
      - jq
      - gnu-sed
      - go
      - php72
      - nkf
      - the_platinum_searcher
      - tree
      - chromedriver
      - awscli
      - lastpass-cli
      - sqlite
      - boost # required by Karabiner-Elements
    homebrew_cask_packages:
      - docker
      - slack
      - atom
      - skitch

